---
- name: Configuration NovaShop PREPROD
  hosts: web
  become: yes

  tasks:
    - name: Installer Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Démarrer Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Déployer NovaShop
      copy:
        src: ../app/index.html
        dest: /var/www/html/index.html